version: '3.8'
services:
  mocks:
    image: stoplight/mokapi
    volumes:
      - ./mocks:/workspace
    ports:
      - "4441:4440"
    command: ["mock", "init"]
  ui:
    build: ./ui-app
    ports:
      - "4442:4440"
